### ISSUE TITLE
Cannot load @rpath/libduckdb.dylib 

### ISSUE THREAD

**Issue by jpkli** [deepcrawl/node-duckdb#69]
Thank you for sharing this awesome work! 

I tried to use node-duckdb, but encountered the following error when using with webpack 5.x and node-loader on Mac OS: 

```
Error: Cannot open /..../build/node-duckdb-addon.node: Error: dlopen(/..../build/node-duckdb-addon.node, 1): Library not loaded: @rpath/libduckdb.dylib
  Referenced from: /.../build/node-duckdb-addon.node
  Reason: image not found
    at Object.../../node_modules/node-duckdb/build/Release/node-duckdb-addon.node (node-duckdb-addon.node:1)
```

I have to manually copy the "libduckdb.dylib" from the node_modules/node-duckdb/build/Release folder to my build folder to work around this error. It would be great if this can be fixed. Thanks again!

**Comment by rostislavdeepcrawl** [comment]
Hi, thanks for the feedback. I believe this is a `node-loader` issue, since it should automatically resolve all the dependencies (like `ncc` for example). But nevertheless, my proposed workaround is to use the `copy-webpack-plugin`:

```
const path = require('path');
const CopyPlugin = require("copy-webpack-plugin");

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  target: 'node',
  node: {
    __dirname: false,
  },
  plugins: [
    new CopyPlugin({
      patterns: [
        { from: "**/*.dylib", to: "[name].[ext]" },
      ],
    }),
  ],
  module: {
    rules: [
      {
        test: /\.node$/,
        loader: 'node-loader',
      },
    ],
  },
};


```

**Comment by jpkli** [comment]
Thank you! We're already using the copy-plugin as a workaround for now.
